##Doki Doki Forces - Unlockable characters! :D

## Enra's and Cyrke's Sayonika definitions
## All the credits of Sayonika belong to sr229 "Enra" (Project Sayonika Designer) and Cyrke (Mascot design)
## These mascot's expressions and sprites are free for you to use in VN under Creative Commons 3.0 Non Commercial.
## Definitions file made by CPG Yuri

# define syka = DynamicCharacter('syka_name', image='syka', what_prefix='"', what_suffix='"', ctc="ctc", ctc_position="fixed")
# default syka_name = "Sayonika"
image syka 1 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/a.png")
image syka 1a = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/a.png")
image syka 1b = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/b.png")
image syka 1c = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/c.png")
image syka 1d = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/d.png")
image syka 1e = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/e.png")
image syka 1f = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/f.png")
image syka 1g = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/g.png")
image syka 1h = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/h.png")
image syka 1i = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/i.png")
image syka 1j = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/j.png")
image syka 1k = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/k.png")
image syka 1l = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/l.png")
image syka 1l2 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/l2.png")
image syka 1m = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/m.png")
image syka 1n = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/n.png")
image syka 1o = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/o.png")
image syka 1p = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/p.png")
image syka 1q = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/q.png")
image syka 1r = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/r.png")
image syka 1s = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/s.png")
image syka 1t = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/t.png")
image syka 1u = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/u.png")
image syka 1v = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/v.png")
image syka 1w = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/w.png")
image syka 1x = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/x.png")
image syka 1y = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/y.png")
image syka 1z = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/1.png", (0, 0), "mod_assets/sayonika/z.png")

image syka 2 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/a.png")
image syka 2a = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/a.png")
image syka 2b = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/b.png")
image syka 2c = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/c.png")
image syka 2d = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/d.png")
image syka 2e = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/e.png")
image syka 2f = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/f.png")
image syka 2g = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/g.png")
image syka 2h = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/h.png")
image syka 2i = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/i.png")
image syka 2j = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/j.png")
image syka 2k = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/k.png")
image syka 2l = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/l.png")
image syka 2l2 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/l2.png")
image syka 2m = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/m.png")
image syka 2n = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/n.png")
image syka 2o = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/o.png")
image syka 2p = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/p.png")
image syka 2q = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/q.png")
image syka 2r = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/r.png")
image syka 2s = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/s.png")
image syka 2t = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/t.png")
image syka 2u = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/u.png")
image syka 2v = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/v.png")
image syka 2w = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/w.png")
image syka 2x = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/x.png")
image syka 2y = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/y.png")
image syka 2z = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r1.png", (0, 0), "mod_assets/sayonika/z.png")

image syka 3 = Image("mod_assets/sayonika/3a.png")
image syka 3a = Image("mod_assets/sayonika/3a.png")
image syka 3b = Image("mod_assets/sayonika/3b.png")
image syka 3c = Image("mod_assets/sayonika/3c.png")
image syka 3d = Image("mod_assets/sayonika/3d.png")
image syka 3e = Image("mod_assets/sayonika/3e.png")
image syka 3f = Image("mod_assets/sayonika/3f.png")
image syka 3g = Image("mod_assets/sayonika/3g.png")
image syka 3h = Image("mod_assets/sayonika/3h.png")
image syka 3i = Image("mod_assets/sayonika/3i.png")
image syka 3j = Image("mod_assets/sayonika/3j.png")
image syka 3k = Image("mod_assets/sayonika/3k.png")
image syka 3l = Image("mod_assets/sayonika/3l.png")

image syka 4 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/a.png")
image syka 4a = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/a.png")
image syka 4b = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/b.png")
image syka 4c = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/c.png")
image syka 4d = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/d.png")
image syka 4e = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/e.png")
image syka 4f = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/f.png")
image syka 4g = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/g.png")
image syka 4h = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/h.png")
image syka 4i = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/i.png")
image syka 4j = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/j.png")
image syka 4k = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/k.png")
image syka 4l = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/l.png")
image syka 4l2 = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/l2.png")
image syka 4m = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/m.png")
image syka 4n = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/n.png")
image syka 4o = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/o.png")
image syka 4p = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/p.png")
image syka 4q = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/q.png")
image syka 4r = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/r.png")
image syka 4s = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/s.png")
image syka 4t = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/t.png")
image syka 4u = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/u.png")
image syka 4v = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/v.png")
image syka 4w = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/w.png")
image syka 4x = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/x.png")
image syka 4y = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/y.png")
image syka 4z = im.Composite((960, 960), (0, 0), "mod_assets/sayonika/2l.png", (0, 0), "mod_assets/sayonika/2r2.png", (0, 0), "mod_assets/sayonika/z.png")

image syka ghost = Image("mod_assets/sayonika/Ghosyonika.png")
image syka orb = Image("mod_assets/sayonika/sayonika_orb.png")
image sk orb = Image("mod_assets/sayonika/sayonika_orb.png")

#Chara
image chara chara1 = "mod_assets/chara/chara.png"
image chara mchara1 = morning(im.Composite((960, 960), (0, 0), "mod_assets/chara/chara.png"))
image chara chara2 = "mod_assets/chara/chara2.png"
image chara mchara2 = morning(im.Composite((960, 960), (0, 0), "mod_assets/chara/chara2.png"))
image chara chara3 = "mod_assets/chara/chara3.png"
image chara chara4 = "mod_assets/chara/chara4.png"
image chara chara5 = "mod_assets/chara/chara5.png"
image chara chara6 = "mod_assets/chara/chara6.png"
image chara chara7 = "mod_assets/chara/chara7.png"
image chara orb = Image("mod_assets/chara/chara_orb.png")

#TsunKrAZy
image tsun 1a = Image("mod_assets/tsun/1a.png")
image tsun 1b = Image("mod_assets/tsun/1b.png")
image tsun 1c = Image("mod_assets/tsun/1c.png")
image tsun 1d = Image("mod_assets/tsun/1d.png")
image tsun 1da = Image("mod_assets/tsun/1da.png")
image tsun 1e = Image("mod_assets/tsun/1e.png")
image tsun 1f = Image("mod_assets/tsun/1f.png")
image tsun 1g = Image("mod_assets/tsun/1g.png")
image tsun 1h = Image("mod_assets/tsun/1h.png")
image tsun 1ha = Image("mod_assets/tsun/1ha.png")
image tsun 1i = Image("mod_assets/tsun/1i.png")
image tsun 1oa = Image("mod_assets/tsun/1oa.png")
image tsun 1q = Image("mod_assets/tsun/1q.png")
image tsun 1qa = Image("mod_assets/tsun/1qa.png")
image tsun 1r = Image("mod_assets/tsun/1r.png")
image tsun 1s = Image("mod_assets/tsun/1s.png")
image tsun 1t = Image("mod_assets/tsun/1t.png")
image tsun 1y = Image("mod_assets/tsun/1y.png")
image tsun 1z = Image("mod_assets/tsun/1z.png")

image tsun 2a = Image("mod_assets/tsun/2a.png")
image tsun 2b = Image("mod_assets/tsun/2b.png")
image tsun 2b2 = Image("mod_assets/tsun/2b2.png")
image tsun 2c = Image("mod_assets/tsun/2c.png")
image tsun 2e = Image("mod_assets/tsun/2e.png")
image tsun 2f = Image("mod_assets/tsun/2f.png")
image tsun 2g = Image("mod_assets/tsun/2g.png")
image tsun 2h = Image("mod_assets/tsun/2h.png")
image tsun 2i = Image("mod_assets/tsun/2i.png")
image tsun 2j = Image("mod_assets/tsun/2j.png")
image tsun 2ja = Image("mod_assets/tsun/2ja.png")
image tsun 2jaa = Image("mod_assets/tsun/2jaa.png")
image tsun 2k = Image("mod_assets/tsun/2k.png")
image tsun 2l = Image("mod_assets/tsun/2l.png")
image tsun 2m = Image("mod_assets/tsun/2m.png")
image tsun 2n = Image("mod_assets/tsun/2n.png")
image tsun 2o = Image("mod_assets/tsun/2o.png")
image tsun 2oa = Image("mod_assets/tsun/2oa.png")
image tsun 2p = Image("mod_assets/tsun/2p.png")
image tsun 2q = Image("mod_assets/tsun/2q.png")
image tsun 2r = Image("mod_assets/tsun/2r.png")
image tsun 2s = Image("mod_assets/tsun/2s.png")
image tsun 2t = Image("mod_assets/tsun/2t.png")
image tsun 2u = Image("mod_assets/tsun/2u.png")
image tsun 2z = Image("mod_assets/tsun/2z.png")

image tsun 3a = Image("mod_assets/tsun/3a.png")
image tsun 3b = Image("mod_assets/tsun/3b.png")
image tsun 3d = Image("mod_assets/tsun/3d.png")
image tsun 3da = Image("mod_assets/tsun/3da.png")
image tsun 3e = Image("mod_assets/tsun/3e.png")
image tsun 3f = Image("mod_assets/tsun/3f.png")
image tsun 3ja = Image("mod_assets/tsun/3ja.png")

image tsun 4a = Image("mod_assets/tsun/4a.png")
image tsun 4f = Image("mod_assets/tsun/4f.png")
image tsun 4i = Image("mod_assets/tsun/4i.png")
image tsun 4ja = Image("mod_assets/tsun/4ja.png")
image tsun 4l2 = Image("mod_assets/tsun/4l2.png")
image tsun 4q = Image("mod_assets/tsun/4q.png")
image tsun 4w = Image("mod_assets/tsun/4w.png")
image tsun 4x = Image("mod_assets/tsun/4x.png")
image tsun 4xa = Image("mod_assets/tsun/4xa.png")
image tsun 4y = Image("mod_assets/tsun/4y.png")
image tsun 4z = Image("mod_assets/tsun/4z.png")

image tsun 6b = Image("mod_assets/tsun/6b.png")
image tsun 6b2 = Image("mod_assets/tsun/6blush.png")
image tsun 6b3 = Image("mod_assets/tsun/6blush2.png")
image tsun 6c = Image("mod_assets/tsun/6c.png")
image tsun 6d = Image("mod_assets/tsun/6d.png")
image tsun 6g = Image("mod_assets/tsun/6g.png")
image tsun 6i = Image("mod_assets/tsun/6i.png")
image tsun 6j = Image("mod_assets/tsun/6j.png")
image tsun 6k = Image("mod_assets/tsun/6k.png")
image tsun 6ka = Image("mod_assets/tsun/6ka.png")
image tsun 6l = Image("mod_assets/tsun/6l.png")
image tsun 6m = Image("mod_assets/tsun/6m.png")
image tsun 6og = Image("mod_assets/tsun/6og.png")
image tsun 6y = Image("mod_assets/tsun/6y.png")

image tsun 7a = Image("mod_assets/tsun/7a.png")
image tsun 7b = Image("mod_assets/tsun/7b.png")
image tsun 7ba = Image("mod_assets/tsun/7ba.png")
image tsun 7c = Image("mod_assets/tsun/7c.png")
image tsun 7ca = Image("mod_assets/tsun/7ca.png")
image tsun 7cb = Image("mod_assets/tsun/7cb.png")
image tsun 7cc = Image("mod_assets/tsun/7cc.png")
image tsun 7dc = Image("mod_assets/tsun/7dc.png")
image tsun 7h = Image("mod_assets/tsun/7h.png")
image tsun 7j = Image("mod_assets/tsun/7j.png")
image tsun 7ja = Image("mod_assets/tsun/7ja.png")
image tsun 7o = Image("mod_assets/tsun/7o.png")
image tsun 7oa = Image("mod_assets/tsun/7oa.png")

image tsun 8a = Image("mod_assets/tsun/a.png")
image tsun 8b = Image("mod_assets/tsun/bd3.png")
image tsun 8c = Image("mod_assets/tsun/bd32.png")
image tsun 8y = Image("mod_assets/tsun/8y.png")
image tsun 8yu = Image("mod_assets/tsun/8yu.png")
image tsun 8yua = Image("mod_assets/tsun/8yua.png")

#Yanderes
image tsun 2ya = Image("mod_assets/tsun/2ya.png")
image tsun 2yb = Image("mod_assets/tsun/2yb.png")
image tsun 2yc = Image("mod_assets/tsun/2yc.png")
image tsun 2yd = Image("mod_assets/tsun/2yd.png")
image tsun 2ye = Image("mod_assets/tsun/2ye.png")
image tsun 2yf = Image("mod_assets/tsun/2yf.png")
image tsun 2yj = Image("mod_assets/tsun/2yj.png")

#Glitched
image tsun 2glitch = Image("mod_assets/tsun/2jglitch.png")
image tsun 2jglitch = Image("mod_assets/tsun/2jglitch.png")
image tsun 2rglitch = Image("mod_assets/tsun/2rglitch.png")
image tsun 4zglitch= Image("mod_assets/tsun/4zglitch.png")
image tsun 1tglitch = Image("mod_assets/tsun/glitch1.png")
image tsun 1tglitch2 = Image("mod_assets/tsun/glitch2.png")
image tsun 1tglitch3 = Image("mod_assets/tsun/glitch3.png")

#Stab
image tsun stab_1 = "mod_assets/tsun/stab/1.png"
image tsun stab_2 = "mod_assets/tsun/stab/2.png"
image tsun stab_3 = "mod_assets/tsun/stab/3.png"
image tsun stab_4 = "mod_assets/tsun/stab/4.png"
image tsun stab_5 = "mod_assets/tsun/stab/5.png"
image tsun stab_6 = LiveComposite((960,960), (0, 0), "mod_assets/tsun/stab/6-mask.png", (0, 0), "tsun stab_6_eyes", (0, 0), "mod_assets/tsun/stab/6.png")

image tsun stab_6_eyes:
    "mod_assets/tsun/stab/6-eyes.png"
    subpixel True
    parallel:
        choice:
            xoffset 0.5
        choice:
            xoffset 0
        choice:
            xoffset -0.5
        0.2
        repeat
    parallel:
        choice:
            yoffset 0.5
        choice:
            yoffset 0
        choice:
            yoffset -0.5
        0.2
        repeat
    parallel:
        2.05
        easeout 1.0 yoffset -15
        linear 10 yoffset -15

#Misc
image tsun uwa = Image("mod_assets/tsun/uwa.png")
image tsun mikTsun = Image("mod_assets/tsun/MikTsun.png")
image tsun mikGotchaTsun = Image("mod_assets/tsun/TsunGotMe.png")
image tsun 2exe = Image("mod_assets/tsun/2exe.png")
image tsun errorexe = Image("mod_assets/tsun/error.png")
image tsun orb = Image("mod_assets/tsun/tsun_orb.png")

#Silver the Hedgehog
image silver orb = Image("mod_assets/silver/silver_orb.png")

image silver silver1 = Image("mod_assets/silver/silver_1.png")
image silver silver2 = Image("mod_assets/silver/silver_2.png")
image silver silver3 = Image("mod_assets/silver/silver_3.png")
image silver silver4 = Image("mod_assets/silver/silver_4.png")
image silver silver5 = Image("mod_assets/silver/silver_5.png")
image silver silver6 = Image("mod_assets/silver/silver_6.png")
image silver silver7 = Image("mod_assets/silver/silver_7.png")
image silver silver8 = Image("mod_assets/silver/silver_8.png")
image silver silver9 = Image("mod_assets/silver/silver_9.png")

image silver silver_glitch = Image("mod_assets/silver/silver_3_glitch.png")

#Mio by yagamirai
image mio 1a = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/a.png")
image mio 1ay = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/ay.png")
image mio 1b = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/b.png")
image mio 1c = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/c.png")
image mio 1d = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/d.png")
image mio 1e = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/e.png")
image mio 1f = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/f.png")
image mio 1g = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/g.png")
image mio 1h = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/h.png")
image mio 1i = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/i.png")
image mio 1j = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/j.png")
image mio 1k = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/k.png")
image mio 1l = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/l.png")
image mio 1m = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/m.png")
image mio 1n = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/n.png")
image mio 1o = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/o.png")
image mio 1p = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/p.png")
image mio 1q = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/q.png")
image mio 1r = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/r.png")
image mio 1s = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/s.png")
image mio 1t = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/t.png")
image mio 1u = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/u.png")
image mio 1v = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/v.png")
image mio 1w = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/w.png")
image mio 1x = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/x.png")
image mio 1y = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/y.png")
image mio 1z = im.Composite((960, 960), (0, 0), "mod_assets/mio/1.png", (0,0), "mod_assets/mio/z.png")

image mio 2a = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/a.png")
image mio 2ay = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/ay.png")
image mio 2b = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/b.png")
image mio 2c = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/c.png")
image mio 2d = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/d.png")
image mio 2e = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/e.png")
image mio 2f = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/f.png")
image mio 2g = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/g.png")
image mio 2h = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/h.png")
image mio 2i = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/i.png")
image mio 2j = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/j.png")
image mio 2k = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/k.png")
image mio 2l = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/l.png")
image mio 2m = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/m.png")
image mio 2n = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/n.png")
image mio 2o = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/o.png")
image mio 2p = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/p.png")
image mio 2q = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/q.png")
image mio 2r = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/r.png")
image mio 2s = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/s.png")
image mio 2t = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/t.png")
image mio 2u = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/u.png")
image mio 2v = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/v.png")
image mio 2w = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/w.png")
image mio 2x = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/x.png")
image mio 2y = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/y.png")
image mio 2z = im.Composite((960, 960), (0, 0), "mod_assets/mio/2.png", (0,0), "mod_assets/mio/z.png")

image mio 3a = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/a.png")
image mio 3ay = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/ay.png")
image mio 3b = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/b.png")
image mio 3c = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/c.png")
image mio 3d = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/d.png")
image mio 3e = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/e.png")
image mio 3f = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/f.png")
image mio 3g = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/g.png")
image mio 3h = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/h.png")
image mio 3i = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/i.png")
image mio 3j = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/j.png")
image mio 3k = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/k.png")
image mio 3l = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/l.png")
image mio 3m = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/m.png")
image mio 3n = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/n.png")
image mio 3o = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/o.png")
image mio 3p = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/p.png")
image mio 3q = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/q.png")
image mio 3r = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/r.png")
image mio 3s = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/s.png")
image mio 3t = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/t.png")
image mio 3u = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/u.png")
image mio 3v = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/v.png")
image mio 3w = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/w.png")
image mio 3x = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/x.png")
image mio 3y = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/y.png")
image mio 3z = im.Composite((960, 960), (0, 0), "mod_assets/mio/3.png", (0,0), "mod_assets/mio/z.png")

image mio 4a = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/a.png")
image mio 4ay = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/ay.png")
image mio 4b = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/b.png")
image mio 4c = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/c.png")
image mio 4d = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/d.png")
image mio 4e = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/e.png")
image mio 4f = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/f.png")
image mio 4g = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/g.png")
image mio 4h = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/h.png")
image mio 4i = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/i.png")
image mio 4j = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/j.png")
image mio 4k = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/k.png")
image mio 4l = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/l.png")
image mio 4m = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/m.png")
image mio 4n = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/n.png")
image mio 4o = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/o.png")
image mio 4p = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/p.png")
image mio 4q = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/q.png")
image mio 4r = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/r.png")
image mio 4s = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/s.png")
image mio 4t = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/t.png")
image mio 4u = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/u.png")
image mio 4v = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/v.png")
image mio 4w = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/w.png")
image mio 4x = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/x.png")
image mio 4y = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/y.png")
image mio 4z = im.Composite((960, 960), (0, 0), "mod_assets/mio/4.png", (0,0), "mod_assets/mio/z.png")

image mio 5a = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/a.png")
image mio 5ay = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/ay.png")
image mio 5b = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/b.png")
image mio 5c = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/c.png")
image mio 5d = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/d.png")
image mio 5e = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/e.png")
image mio 5f = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/f.png")
image mio 5g = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/g.png")
image mio 5h = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/h.png")
image mio 5i = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/i.png")
image mio 5j = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/j.png")
image mio 5k = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/k.png")
image mio 5l = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/l.png")
image mio 5m = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/m.png")
image mio 5n = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/n.png")
image mio 5o = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/o.png")
image mio 5p = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/p.png")
image mio 5q = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/q.png")
image mio 5r = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/r.png")
image mio 5s = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/s.png")
image mio 5t = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/t.png")
image mio 5u = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/u.png")
image mio 5v = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/v.png")
image mio 5w = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/w.png")
image mio 5x = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/x.png")
image mio 5y = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/y.png")
image mio 5z = im.Composite((960, 960), (0, 0), "mod_assets/mio/5.png", (0,0), "mod_assets/mio/z.png")

image mio 6a = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/a.png")
image mio 6ay = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/ay.png")
image mio 6b = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/b.png")
image mio 6c = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/c.png")
image mio 6d = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/d.png")
image mio 6e = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/e.png")
image mio 6f = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/f.png")
image mio 6g = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/g.png")
image mio 6h = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/h.png")
image mio 6i = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/i.png")
image mio 6j = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/j.png")
image mio 6k = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/k.png")
image mio 6l = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/l.png")
image mio 6m = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/m.png")
image mio 6n = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/n.png")
image mio 6o = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/o.png")
image mio 6p = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/p.png")
image mio 6q = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/q.png")
image mio 6r = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/r.png")
image mio 6s = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/s.png")
image mio 6t = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/t.png")
image mio 6u = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/u.png")
image mio 6v = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/v.png")
image mio 6w = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/w.png")
image mio 6x = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/x.png")
image mio 6y = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/y.png")
image mio 6z = im.Composite((960, 960), (0, 0), "mod_assets/mio/6.png", (0,0), "mod_assets/mio/z.png")

image mio 7a = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/a.png")
image mio 7ay = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/ay.png")
image mio 7b = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/b.png")
image mio 7c = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/c.png")
image mio 7d = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/d.png")
image mio 7e = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/e.png")
image mio 7f = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/f.png")
image mio 7g = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/g.png")
image mio 7h = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/h.png")
image mio 7i = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/i.png")
image mio 7j = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/j.png")
image mio 7k = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/k.png")
image mio 7l = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/l.png")
image mio 7m = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/m.png")
image mio 7n = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/n.png")
image mio 7o = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/o.png")
image mio 7p = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/p.png")
image mio 7q = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/q.png")
image mio 7r = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/r.png")
image mio 7s = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/s.png")
image mio 7t = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/t.png")
image mio 7u = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/u.png")
image mio 7v = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/v.png")
image mio 7w = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/w.png")
image mio 7x = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/x.png")
image mio 7y = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/y.png")
image mio 7z = im.Composite((960, 960), (0, 0), "mod_assets/mio/7.png", (0,0), "mod_assets/mio/z.png")

image mio 8a = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/a.png")
image mio 8ay = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/ay.png")
image mio 8b = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/b.png")
image mio 8c = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/c.png")
image mio 8d = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/d.png")
image mio 8e = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/e.png")
image mio 8f = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/f.png")
image mio 8g = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/g.png")
image mio 8h = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/h.png")
image mio 8i = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/i.png")
image mio 8j = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/j.png")
image mio 8k = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/k.png")
image mio 8l = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/l.png")
image mio 8m = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/m.png")
image mio 8n = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/n.png")
image mio 8o = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/o.png")
image mio 8p = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/p.png")
image mio 8q = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/q.png")
image mio 8r = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/r.png")
image mio 8s = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/s.png")
image mio 8t = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/t.png")
image mio 8u = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/u.png")
image mio 8v = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/v.png")
image mio 8w = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/w.png")
image mio 8x = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/x.png")
image mio 8y = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/y.png")
image mio 8z = im.Composite((960, 960), (0, 0), "mod_assets/mio/8.png", (0,0), "mod_assets/mio/z.png")

image mio orb = Image("mod_assets/mio/mio_orb.png")